import { Router } from 'express';
import { Patient } from '../models/index.js';
import { createController } from '../controllers/generic.controller.js';
const router = Router();
const c = createController(Patient);
router.post('/', c.create);
router.get('/', c.all);
router.get('/:id', c.one);
router.put('/:id', c.update);
router.delete('/:id', c.remove);
export default router;
